#PROGRAM TO FIND THE HYPOTENUSE OF THE RIGHT ANGLED TRIANGLE WHEN THE BASE AND HEIGHT ARE ENTERED BY THE USER
b=int(input("ENTER THE BASE OF RIGHT ANGLED TRIANGLE:-"))
h=int(input("ENTER THE HEIGHT OF RIGHT ANGLED TRIANGLE:-"))
h=(b*b)+(h*h)
print("THE HYPOTENUSE OF RIGHT ANGLED TRIANGLE IS=",h)
